// <auto-generated />
namespace Accounting_Final_Details.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class wearhouseTableAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(wearhouseTableAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202110110809027_wearhouseTableAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
